---
name: "Quantifying Process Variations and Its Impacts on Smartphones"
published: ispass
people:
- gurupras
- shaseley
- mark@ece.tufts.edu
- challen
projects:
- poweragility
funding:
- 2014-csr-poweragility
---
== Abstract

Process variation can cause the performance and energy consumption of
smartphones of the same model to vary significantly. While process variation
has been studied in detail, the effects on smartphone performance have not been
quantified and evaluated. In this work we study the performance and energy
differences of 5 recent SoC generations caused by underlying process variation.

We make two important contributions. First, we present a methodology to
construct a temperature-stabilized environment to perform repeatable power and
performance measurements. Studying power-performance characteristics of
smartphones is difficult. Running a benchmark back-to-back often produces
significantly different results due to heat. Temperature, both device and
ambient, play a significant role in determining performance and energy. Our
methodology allows us to control for various factors and isolate the effects of
the underlying process variation. We then apply our methodology to investigate
performance and energy characteristics of several recent generations of
smartphone CPUs that result from process variation. Our results show that
devices of the same model may exhibit differences of 10% and 12% difference in
performance and energy over a fixed-duration workload.

