---
name: "Quantifying Process Variations and Its Impacts on Smartphones"
published: ispass
people:
- gurupras
- shaseley
- mark@ece.tufts.edu
- challen
projects:
- poweragility
funding:
- 2014-csr-poweragility
---
== Abstract

Consumers, app developers, and many mobile systems researchers expect two
identical smartphones to perform similarly.
//
But transistor process variation can cause one device to heat up much more
rapidly than another.
//
As a consequence, this device may exhibit up to 20% performance and energy
consumption difference despite the fact that consumers and experiments would
have considered the two devices identical.

We make two important contributions to the understanding of temperature effects
on today's mobile devices.
//
First, we present results from carefully-controlled studies exploring the
relationships between transistor quality, temperature, energy, and performance.
//
Second, we have developed a novel way to expose normally-hidden information
about transistor quality to consumers.
//
Our approach is able to rank device transistor quality with a mean absolute
error of less than 9 percentile-points for the Nexus 5 and 15 percentile-points
for the Nexus 6.
//
Furthermore, we are able to define equivalence classes based on transistor
quality and classify devices within 96% accuracy at room temperature.
//
It can be easily used by consumers to test the quality of their device, and by
researchers to ensure that devices used in experiments are in fact equivalent.
