language: node_js
node_js:
  - "6.9.4"
dist: trusty
sudo: false
notifications:
  webhooks:
    urls:
      - https://www.bluegroup.systems/notifications
    on_start: always
    on_success: never
    on_failure: never

# vim: ts=2:sw=2:et
