---
name: "CI-SUSTAIN: Collaborative Research: Sustaining Successful Smartphone
Testbeds to Enable Diverse Mobile Experiments"
link: "http://www.nsf.gov/awardsearch/showAward.do?AwardNumber=1629894"
abstract: "http://www.nsf.gov/awardsearch/showAward.do?AwardNumber=1629894"
started: 2016-09-01
ends: 2017-09-01
amount: 75000
source: NSF
program: CRI
rate: 12
faculty:
- challen
- zmao@umich.edu
- qiao
students:
- jinghaos
projects:
- phonelab
spelling_exceptions:
- MobiLab
---
== Funding Note

Funding for this proposal was cut dramatically.
//
As a result, only the lead organization (UB) received support from this award
for the https://www.phone-lab.org[PhoneLab] project and no support was
provided to the University of Michigan for
http://mobilab.eecs.umich.edu/[MobiLab].
//
Due to the changes required by the lower funding level, only the public award
abstract is included below and no copy of the proposal as submitted is
provided.
//
In this case, the public award abstract does a much better job of describing
the reduced scope of the funded project.

== Public Award Abstract

Today, smartphones are everywhere: connecting, informing, guiding,
quantifying, and entertaining us.
//
Vibrant smartphone software marketplaces put million of useful apps created by
developers around the world at our fingertips.
//
But while anyone can develop and deploy a smartphone app, apps rely on
functionality provided by the underlying smartphone platform and operating
system.
//
The smartphone platform software is responsible conserving energy and
prolonging battery lifetime, determining what network connection to use to
balance speed and cost, accurately and efficiently determining the device's
location, and other critical tasks.
//
How well it performs these functions affects all installed apps.
//
And yet, the smartphone platform is closely controlled by smartphone vendors
and so very difficult for researchers to modify or improve.
//
https://www.phone-lab.org[PhoneLab] addresses this experimental gap by
allowing systems and networking researchers to modify the smartphone platform
installed on several hundred users' primary smartphones.

PhoneLab consists of several hundred University at Buffalo affiliates who act
as participants.
//
Participants carry smartphones running a custom Android platform image
maintained by PhoneLab administrators.
//
The PhoneLab platform image is maintained in collaboration with the mobile
systems and networking community.
//
At any point it contains a mixture of instrumentation to generate datasets as
well as novel features and new capabilities that are being evaluated.
//
Once projects are reviewed for human subjects safety, researchers can download
datasets generated by their experiments or by previous experiments.
//
PhoneLab participants are incentivized to join ongoing experiments by a
discounted service plan provided by Sprint.
//
During this project period PhoneLab will be continuing to migrate from
external to community sustainability while also improving our existing Android
instrumentation.
