---
working: true
spelling_exceptions:
  - Br'er
  - briar
  - Siebel
---

== Into the Briar Patch

[.snippet]
//
--
//
[.lead]
//
As a child I was told the story of
//
https://en.wikipedia.org/wiki/Br%27er_Rabbit[Br'er Rabbit].
//
We must have had it as a picture book, since I clearly remember drawings of
the
//
https://en.wikipedia.org/wiki/Tar-Baby[Tar Baby]
//
that Br'er Fox used to trap Br'er Rabbit.
//
But I also remember the panel depicting the final plot twist.
//
After Br'er Rabbit begs Br'er Fox _not_ to throw him into the briar patch,
Br'er Fox does exactly that.
//
And then watches as Br'er Rabbit lounges and laughs triumphantly in the
brambles.
//
"Br'er Fox: rabbits are _born_ in a briar patch", he exults.

Seven months after being
//
link:/posts/2016-10-22-the-best-way-to-not-get-tenure/[unceremoniously tossed
out]
//
of my department, I've landed somewhere that feels much more comfortable.
//
This fall I'll join the
//
https://cs.illinois.edu/[Computer Science Department] at the
//
http://illinois.edu/[University of Illinois at Urbana-Champaign]
//
as an Associate Teaching Professor.
//
I'm looking forward to a better fit in a much better department, and to the
chance to focus my creative energies on improving education at scale.
//
--

=== A Thornier Future

One of the first things that my wife Suzanna told me when I relayed the tenure
vote last October was that our lives were going to change forever.
//
She was right&mdash;but it was a slow process.
//
My
//
link:/posts/2016-10-22-the-best-way-to-not-get-tenure/[original blog post]
//
provoked a surprising outpouring of supportive emails which I remain extremely
grateful for.
//
But there were still two more months in an already-long fall semester.
//
I had to finish the exhausting first iteration of
//
link:/courses/ub-199-fall-2016/[my large flipped class on the internet].
//
There were projects to keep working on, students to supervise, and papers to
submit.
//
So by the time mid-December rolled around, I was ready to drop.
//
And it was past time to apply for my next job.

When I started looking for new faculty jobs, I didn't immediately consider
instructional positions.
//
My own experience with teaching faculty jobs was that they were overworked and
both underpaid and underappreciated.
//
I had seen first-hand how handling multiple large courses left teaching
faculty with little time to maintain existing courses&mdash;much less plan
improvements or experiment with new ideas or tools.
//
So I ended up applying to a mixture of teaching and research faculty
positions.

But as I found out more about teaching faculty jobs at other institutions, I
grew more excited.
//
I think I might have actually giggled out loud after one teaching faculty at
an excellent-but-to-remain-unnamed school described their teaching load.
//
"I'm handling that as a pre-tenure research faculty this year", I remember
thinking.

Once I started writing cover letters for teaching faculty jobs, my difference
in enthusiasm became clear.
//
I've always struggled a bit to justify my work on mobile systems.
//
I have no such difficulties
//
https://goo.gl/Qa9lWM[explaining my excitement]
//
about improving education.
//
The briar patch was looking mighty comfy.

My timing was pretty good.
//
Computer science departments across the country are experiencing exponential
surges in enrollment&mdash;and greeting those increases with a mixture of
excitement and trepidation that varies from institution to institution.
//
(More on that in a later post.)
//
So many departments are looking for teaching faculty to help keep with recent
rapid growth.
//
I ended with eight on-campus interviews, of which I did seven, and receiving
four strong job offers.

=== A Fresh Patch

That left Suzanna and me with a very tough decision.
//
Every offer had different pros and cons, and none was a clear winner in every
category.
//
So we talked about it.
//
And talked about it.
//
And talked about it some more.
//
We made lists.
//
We did pair-wise face offs.
//
We got it down to three, and then to two&mdash;just to see it creep back up to
three, and almost to four.
//
We made a decision.
//
And then unmade it a few days later.
//
And the made the same decision again.
//
And then saw it survive on last strong challenge, aided at least partly by a
very well-timed formal offer letter.

But every time we made a decision, it came out the same way: the University of
Illinois.
//
There are many things I love about https://cs.illinois.edu/[CS@Illinois].
//
It's a
//
http://csrankings.org/[top-tier department]
//
at a public school that's dominant on campus and housed in a
//
https://en.wikipedia.org/wiki/Thomas_M._Siebel_Center_for_Computer_Science[huge, beautiful, and brand-new building]
//
footnote:[Put more succinctly: at Illinois, CS _rules_&mdash;in both senses of
the word.].
//
The students and faculty are excellent, including a great cadre of teaching
faculty that are excited about the challenges of education at scale.
//
My interactions with department leadership have shown them to be thoughtful
and reasonable.

But there were two things about Illinois that really stood out to me.
//
First, they are taking steps to take teaching faculty seriously.
//
All four of my offers were for associate-level teaching faculty positions.
//
But only Illinois took the time to complete a formal promotion process, which
included soliciting external letters.
//
Their promotional criteria are also excellent, and include consideration of
external impact as well as classroom excellence.
//
If I am fortunate enough to be promoted to (Full) Teaching Professor at
Illinois, it will be more than just social promotion footnote:[Someone at UB
once told me that teaching faculty in my former department only got promoted
by threatening to quit.].
//
Contract length and pay equity are still areas of concern, but the department
seems headed in the right direction, if somewhat constrained by broader
university policies.

Second, they are doing really well at attracting women to computer science.
//
https://cs.illinois.edu/news/46-incoming-computer-science-majors-uiucs-college-engineering-are-women[A full _46%_ of their incoming computer scientists last year (2016) are female],
//
an astonishing number given that the national average is
//
https://ngcproject.org/statistics[around 18%].
//
To be clear, this number comes with a few caveats: it's only within the CS
major and drops to 36% when you consider all students studying computer
science, and of course gender is just one of many ways in which students
studying computer science are unrepresentative of the broader population.
//
But still, this is impressive progress, and creates the opportunity to start
to tackle some of those other tough representation issues&mdash;including race
and socioeconomic status.

The diversity of the student body speaks strongly to the health of a computer
science department footnote:[I wish that ABET would figure this out, and stop
being fooled by the wildly unrepresentative Potempkin student panels that
departments assemble for visits.].
//
If we've learned anything from all of the efforts by all of the departments
that have tried to address this issue, it's that there is no silver bullet.
//
Improving diversity requires a comprehensive effort, including effective high
school outreach, strong introductory courses, emphasis on impact throughout
the curriculum, a welcoming departmental culture, and extra support to help
bootstrap groups that may not immediately feel like they fit in.
//
Getting this right demonstrates both teamwork and a commitment to the
department's educational mission.

=== Tossed

So I'm happy where I landed.
//
And as one of my new colleagues was brave enough to put it when I interviewed,
this may end up being the best worst thing that has ever happened to me.

But it was still awful.
//
Suzanna and I are leaving behind friends, a house, and a neighborhood that we
love.
//
I'm walking away from a new curriculum that I helped formulate and courses
that I perfected, created, or designed.
//
My lab is splitting up, with a few of my students finishing in place, a few
moving to other advisers, and at least one that will move with me to Illinois.

One of the hardest parts for me was that I received no feedback after the
department's vote.
//
Feedback is at the heart of how scientists evaluate each other, with written
reviews accompanying every rejected paper and declined grant.
//
And yet, none of the eight faculty that voted against me have identified
themselves or offered any explanation.
//
Neither has anybody else.
//
Tenure is supposed to represent a final and ultimate professional
evaluation&mdash;a permanent decision laboriously and carefully made.
//
But in UB's CS department, that decision comes with less justification than I
provide when reviewing papers for second-tier conferences.

Without an explanation, it's easy to engage in speculation.
//
I did a fair amount of that, most of it private, some of it wild, none of it
convincing.

// vim: ts=2:sw=2:et
