---
working: true
spelling_exceptions:
  - codecademy
---

== Flipping a Large Class: Part 2

[.snippet]
//
--
//
[.lead]
//
For me, the most daunting part of flipping a large class was designing
activities.
//
Whatever else you may say about lecturing, it is a _great_ way to kill time.
//
When you flip a class, all of those hours that you could have easily filled
lecturing, now have to be spent doing something else--but what?
//
Below I attempt to share what we learned developing and deploying 24 new
activities as part of our new
//
link:/courses/ub-199-fall-2016[course on the internet].

This is the second part of a planned three-part series
//
footnote:[Although it may sprawl past that...].
//
link:/posts/2016-12-22-flipping-a-large-class-part-1/[Part one]
//
focused on the logistical challenges of flipping a large class.
//
Part three will describe the video delivery system we built.
//
[.readmore.remove]#Read more...#
//
--

=== Background

If you didn't read
//
link:/posts/2016-12-22-flipping-a-large-class-part-1/[part one of this series],
//
it may be worth it before continuing.
//
Or at least skim the
//
link:/posts/2016-12-22-flipping-a-large-class-part-1/#what_is_a_our_flipped_classroom[overview of our flipped classroom approach].
//
As a brief review, students in our
//
link:/courses/ub-199-fall-2016[new course on the internet]
//
were required to watch around 20 5-minute video lessons outside of class each
week.
//
During two hours of scheduled meeting time, students worked on activities in
groups of two or four, supervised by the course staff.
//
We referred to these meetings as _activity sections_ to distinguish them from
lectures.
//
Attendance was taken at the activity sections and participation was a fairly
large portion of students' grades.
//
So students tended to show up.

=== Not Killing Time

The attraction of the flipped classroom model is that you don't waste class
time on one-to-many content delivery.
//
Once you pass a certain class size, there's not much difference
between students sitting in lecture hall versus at home in front of YouTube footnote:[Hopefully in their bathrobes!].

Consider the following back-of-the-envelope calculation.
//
Assume I can engage 10 different students in some way during each hour-long
lecture--typically by asking them a question.
//
That's a pretty good result even for a lecturer that is pretty talented at
classroom management.
//
Then in a 15-week 3-hours-per-week 100-student class, I'll get to each
student about 4 times per semester--or once _every four weeks_.
//
That's just not that much interaction.
//
And double the class to 200 students--like my OS class next term--and you're
down to _twice a semester_.
//
So you're just not losing that much in the way of interaction by moving
lectures online
//
footnote:[And yes--I'm assuming you can use technology to replace other
features of lecturing, like allowing students to ask questions and the
instructor to gauge the progress of the class.].

So lecture content delivery seems better done online.
//
[.pullquote]#But then: what _do you do_ in class?#
//
For me, this has been a major stumbling block when considering flipping
classes in the past.
//
Consider the process of transitioning a traditional lecture-based course to a
flipped approach.
//
Typically, not only do you need to record new video content, but you also have
to plan activities
//
footnote:[Of course, you don't have to plan activities.
//
Sometimes it would be better to simply move lectures online and not meet in
large groups at all--possibly while preserving other components of the class.
//
But try convincing students and their parents that this is worth their
hard-earned tuition dollars.]
//
to fill the now-empty class time.
//
So it's a double whammy of extra work.
//
The truth is, I've actually wanted to try flipping my OS class for years.
//
And I actually have years of lecture videos already recorded.
//
But the activity preparation part has always scared me off.

Based on what goes on at most universities, I suspect I'm not alone.
//
Part of the problem is how research-focused Ph.D. students are trained.
//
Lecturing is a lot like giving research presentations at conferences, which
graduates students are both trained to do and to care about.
//
Designing activities or assignments is not something graduates students are
trained to do or care about.

As an aside, recently I interviewed for a new job at another institution
footnote:[...that turned out to be far too similar to my current institution].
//
I gave a https://goo.gl/8Q9l9o[good talk] about my group's
link:/projects/[research projects].
//
Afterward, my host said: "Your talk was excellent. Obviously teaching would
not be a problem."
//
That's the all-too-common assumption: if you can give a good research talk,
you can lecture, and if you can lecture, you can teach.
//
But it ignores most of the work that goes into deploying excellent courses:
designing and grading assignments and exams; recruiting, training, and leading
a course staff; finding ways to motivate students; effectively using
technology; etc.

=== Our `internet-class.org` Activities

Before I start discussing our experiences developing the activities,
//
https://www.internet-class.org/courses/fys/syllabus/#_outline[here is the list
of 24 activities that we used].
//
We aimed for a variety reflecting the diversity of the course material.
//
Some activities were https://goo.gl/XIgNXO[scavenger hunts].
//
Others had students https://goo.gl/7gddaN[using command line UNIX networking
utilities].
//
Others had students https://goo.gl/Fq4VSV[playing online (security) games], or
https://goo.gl/MRV3oZ[using existing online tutorials]
(https://www.codecademy.com/[codecademy]).
//
Others had students https://goo.gl/896Lc9[learning about parallel processing
using decks of cards] or https://goo.gl/Wf1cvD[routing using toothpicks and
marshmallows].

We started the semester aiming to have students work primarily in groups of
four.
//
However, we discovered that some of the computer-based activities didn't work
well in groups that large.
//
So we started pairing students for those activities.

We also started out shuffling students into new groups for every activity.
//
However, students complained about this and expressed interest in working in
groups for a bit longer.
//
Rotating groups more quickly allowed students to meet more students--which was
worthwhile, given that this was a freshman-level course--and escape bad groups
more quickly.
//
However, rotating more slowly allowed students to leverage existing
relationships and familiarity with their team members.
//
In the end, we settled on one rotation per week based on a student survey.
//
Many weeks we started with a less computer-based activity on Monday in fours
and then had a more computer-based activity on Wednesday in pairs--but with
students at the same table of four from Monday.

=== Too Hot or Too Cold

[.pullquote]#Overall what we discovered is that designing new activities for a
flipped class is really, really hard.#
//
And it's hard in ways that are quite different from the challenges that you
might encounter designing a traditional lecture and assignment based course.

The first challenge is designing activities that reliably span a certain
length of time.
//
If the activity is too short, students that finish early don't feel like they
got their money's worth.
//
If the activity is too long, students that don't finish get discouraged and
feel like they didn't learn what they were supposed to.
//
We tried--and received complaints about--activities that fell into both
categories.

What this really reflects is a problem I've always been aware of when I
lecture.
//
At any given point, some students are lost, others are bored, and others are
engaged--because I'm either going too fast, too slow, or at the perfect pace.
//
What percentage of the class falls into each category changes minute to
minute, lecture to lecture, and year to year.
//
But what's constant is that I _never have any idea how many students are in
each group_.
//
In the past I've considered try to address this problem through technology.
//
But even if I know how many students are in each group, that doesn't mean that
there is an effective response when half are lost and half are bored.
//
And armed with a semester's worth of lectures, it's easy to reliably fill
every classroom hour.
//
If I'm moving a bit quicker than expected, we can continue with some of
tomorrow's material today.
//
And if I'm moving a bit slower, we can continue with today's material
tomorrow.

Hopefully this analogy also points out part of what makes designing activities
with the right length so hard.
//
The problem isn't just with the activities--it's also with the students.
//
Some of the 440 students in our class weren't sure what operating system their
computer was running.
//
Others already knew multiple programming languages and were contributing to
open-source C++ projects.
//
We tried to mitigate differences between groups by shuffling them each week.
//
And yet, more often than not, we'd have groups packing up to leave 10 minutes
early, while others only completed half of the activity.

And obviously this problem is only going to get worse as computer science
moves into some high schools and some students take advantage of online
resources.
//
So there's a fun new technological problem to solve--creating activities that
can adaptively scale based on student progress to fill a given amount of time.
//
Grouping students by ability may be worthwhile to help ensure that one student
doesn't end up dominating while another is lost.

=== Active Isn't Passive

// vim: ts=2:sw=2:et
