---
name: Qoe-Centric Mobile Operating System Design
published: mobisys
people:
- shaseley
- challen
git: https://blue.cse.buffalo.edu/gitlab/shaseley/posters.mobisys2016-qoe.git
projects:
- qoe
funding:
- 2014-csr-poweragility
poster: true
spelling_exceptions:
  - QoE-centric
---
== Abstract

Current operating systems are already proficient at managing certain system
resources, such as the CPU, memory, and disk.
//
But on interactive mobile devices, users care more about resources such as
time, battery life, and money, that are unmanaged or poorly managed by
today's smartphone platforms.
//
When apps slow down our typing, they waste our time.
//
When apps download unnecessary resources, they waste battery life and
potentially money, if using a metered data plan.
//
It is the degree to which mobile devices effectively manage these
human-facing resources that determines a user's _quality of experience_
(QoE), and it is QoE which should drive not just policy, but decisions on
mobile devices.

While modern operating systems such as Android make decisions based on
policies meant to improve QoE, it is unclear that these static policies
always result in the right decisions.
//
To remedy this, we propose designing QoE-centric mobile operating systems
that use QoE as input to drive resource allocation decisions.
