---
name: "PhoneLab: A Large Programmable Smartphone Testbed"
published: sensemine
people:
- ans25
- anudipam
- tki
- mbulut
- demirbas
- tkosar
- qiao
- stevko
- challen
git: https://github.com/gchallen/papers.sensemine2013-phonelab
projects:
- phonelab
funding:
- 2011-gra-phonelab
invited: true
---
== Abstract

As smartphones have emerged as the most widely deployed mobile computing
platform, the scale of smartphone experimentation has lagged behind. New
facilities enabling large-scale experiments are needed to ensure that
research discoveries translate to the billions of smartphones in use today.
To meet this challenge, we introduce PhoneLab, a 288-device smartphone
testbed deployed at the University at Buffalo. PhoneLab provides access to
smartphone users incentivized to participate in experiments while simplifying
experiment data collection. The testbed will open for public experimentation
in October, 2013, and continue to expand in 2014. To demonstrate the power of
PhoneLab, we present three selected results from a usage characterization
experiment run on 115 phones for 21 days. We use each result to motivate a
future PhoneLab experiment, demonstrating how PhoneLab will enable mobile
systems research. 
