---
title: Teaching Portfolio
layout: portfolio.hbt
goGithub: true
omitTop: true
spelling_exceptions:
- autograder
- 72x
- syllabi
- HotCRP
- P1
- P2
- codecademy
- SUNY
---
:linkattrs:

[.lead]
//
This page summarizes my teaching accomplishments at the University at Buffalo
(UB).

I have pursued a variety of teaching activities at UB.
//
I adapted an existing course on https://www.ops-class.org/[computer operating
systems] to be more efficient and improved it repeatedly over 6 years.
//
I designed and deployed a https://www.internet-class.org/[new flipped course
on the internet] and taught it to 440 freshman.
//
I supervised a https://goo.gl/w8J5u3[complete revision of our undergraduate
curriculum] and contributed designs for https://goo.gl/brdQOO[two new
introductory programming courses].
//
I led the development of several new tools to support these efforts, including
https://test161.ops-class.org/[autograding] and
https://github.com/internet-class/www[video delivery software].

Much of what follows narrates material that is already available online.
//
My link:/courses/[courses page] has a great deal of information about every
class I have taught, including links, syllabi, and student evaluations.
//
Both of my main undergraduate courses have their own
websites&mdash;https://www.ops-class.org[`ops-class.org`] and
https://www.internet-class.org[`internet-class.org`].
//
My link:/projects/[projects page] describes several of my group's experimental
education projects, including software support for
link:/projects/internetclass/[`internet-class.org`] and
link:/projects/opsclass/[`ops-class.org`].
//
And my
//
link:/people/challen@buffalo.edu/GeoffreyChallen-CV.pdf[CV] and
//
link:/people/challen@buffalo.edu/GeoffreyChallen-Teaching.pdf[teaching],
//
link:/people/challen@buffalo.edu/GeoffreyChallen-Improvement.pdf[course
improvement],
//
link:/people/challen@buffalo.edu/GeoffreyChallen-Research.pdf[research],
//
link:/people/challen@buffalo.edu/GeoffreyChallen-Diversity.pdf[diversity],
//
and
//
link:/people/challen@buffalo.edu/GeoffreyChallen-Service.pdf[service]
//
statements are all available online.

== Overview of Courses Taught

I have taught courses to freshman, seniors, and beginning and advanced
graduate students.

=== CSE 199: How the Internet Works

CSE 199 is a freshman-level course on the internet.
//
I designed and deployed all content and materials for this flipped-format
course.
//
It was taught for the first time in Fall 2016 to 440 freshman.

* https://www.internet-class.org[*Website*]
* https://www.internet-class.org/courses/fys/syllabus/[*Example Syllabus*]
* https://goo.gl/oQRerI[*All Course Videos*]
* *Iterations*:
//
link:/courses/ub-199-fall-2016/[Fall 2016]

=== CSE 421/521: Introduction to Operating Systems

CSE 421/521 is a joint undergraduate and graduate level course.
//
It enrolls primarily junior and senior undergraduates and Masters-level
graduate students.
//
I adapted the OS/161 assignments from Harvard and created the
https://test161.ops-class.org[`test161`] autograding system to grade them.
//
I have taught this class every spring since 2012 to between 100 and 200
students.

(Please note that link:/people/carlnues/[Carl Nuessle] has been lecturing
frequently in Spring 2017 while I have been traveling for job interviews.)

* https://www.ops-class.org[*Website*]
* https://www.ops-class.org/courses/buffalo/CSE421_Spring2017/[*Example Syllabus*]
* https://goo.gl/nepnjM[*Course YouTube Channel*]
* https://www.ops-class.org/slides/[*Slides*]
* https://www.ops-class.org/asst/overview/[*Assignments*]
* https://www.ops-class.org/exams/[*Exams*]
* *Iterations*:
//
link:/courses/ub-421-spring-2017/[Spring 2017],
//
link:/courses/ub-421-spring-2016/[Spring 2016],
//
link:/courses/ub-421-spring-2015/[Spring 2015],
//
link:/courses/ub-421-spring-2014/[Spring 2014],
//
link:/courses/ub-421-spring-2013/[Spring 2013],
//
link:/courses/ub-421-spring-2012/[Spring 2012]

=== CSE 622: Advanced Computer Systems

For two years I co-taught a 20-student course on advanced computer systems,
primarily to Masters students.
//
The course focused on introducing students to mobile systems research
literature and having them rapidly prototype and build a novel computer
system.

* *Iterations*:
//
link:/courses/ub-622-fall-2012/[Fall 2012],
//
link:/courses/ub-622-fall-2011/[Fall 2011].

=== CSE 72x: Special Topics in Mobile Systems

Since 2013 I have taught a small seminar on rotating advanced topics in mobile
systems.
//
The course usually enrolls a handful of Ph.D. students.
//
We read research papers together and provide students the opportunity to
contribute to one of my group's active research projects.

* *Iterations and Topics*:
//
link:/courses/ub-720-fall-2013/[Fall 2013 (Smartphone Sustainability)],
//
link:/courses/ub-720-fall-2014/[Fall 2014 (Personal Cloud Computing)],
//
link:/courses/ub-720-fall-2015/[Fall 2015 (Using Uncertainty to Program Mobile
Systems)],
//
link:/courses/ub-720-fall-2016/[Fall 2016 (Improving Smartphone Quality of
Experience)].

== Evidence of Instructional Excellence

Below I provide evidence that I have succeeded in deploying excellent and
effective undergraduate courses.
//
I discuss my work inside and outside the classroom on specific courses,
contributions to curriculum development and improvements, and a variety of
other educational accomplishments.

=== Classroom Instruction

At UB I am known as an engaging and popular classroom instructor.
//
I have been recording my https://www.ops-class.org[operating systems] lectures
since 2012, resulting in hundreds of hours of lecture content available on my
https://www.youtube.com/channel/UCzntthQN6ZF01rRRWikcmmQ[YouTube channel].
//
My channel has almost 3,000 subscribers and my videos have been viewed over
227,000 times.
//
Course and instructor rankings for my https://www.ops-class.org[operating
systems] course are regularly among the highest in the department, despite the
course's reputation as being extremely challenging.

=== Course Improvements

I have led several efforts aimed at improving existing courses and pioneering
new instructional techniques.

*CSE 421/521*

To support more effective autograding for my
https://www.ops-class.org[operating systems course], I initiated the
development of the https://test161.ops-class.org[`test161`] OS/161 autograder.
//
The design of https://test161.ops-class.org[`test161`] benefits from the many
years of experience I had with OS/161-based operating systems courses&mdash;as
a student, teaching assistant, and instructor.
//
It also addressed many of the problems that we encountered in early efforts to
develop autograding systems for OS/161 kernels.

The https://test161.ops-class.org[project web page] has more details about its
design and implementation.
//
But it has proved extremely effective in helping students with the challenging
https://www.ops-class.org/asst/overview/[OS/161 operating systems
assignments].
//
Spring 2017 is the time that I have taught
https://www.ops-class.org/courses/buffalo/CSE421_Spring2017/["CSE 421/521: Introduction to Operating Systems"] with
https://test161.ops-class.org[`test161`] stable from the beginning of the
course footnote:[It was under development in Spring 2016.].
//
Student performance on the assignments has improved dramatically from prior
years.

*CSE 199*

In Fall 2016 I designed and deployed a new course on the internet in a large
flipped format.
//
Several aspects of the course were novel.
//
Course material was divided into https://goo.gl/oQRerI[5-minute videos],
making it easy for other faculty, industry collaborators, and students to
contribute content.
//
We built a https://github.com/internet-class/www[new video delivery system] to
support this format, as well as a number of tools to simplify the process of
recording and organizing such a large video library.

Class time was devoted to hands-on activities introducing students to a
variety of internet concepts, as well as tools and environments that they
would need to learn to use to succeed in future courses.
//
https://www.internet-class.org/courses/fys/syllabus/#_outline[Here is the list
of 24 activities that we used].
//
We aimed for a variety reflecting the diversity of the course material.
//
Some activities were https://goo.gl/XIgNXO[scavenger hunts].
//
Others had students https://goo.gl/7gddaN[using command line UNIX networking
utilities].
//
Others had students https://goo.gl/Fq4VSV[playing online (security) games], or
https://goo.gl/MRV3oZ[using existing online tutorials]
(https://www.codecademy.com/[codecademy]).
//
Others had students https://goo.gl/896Lc9[learning about parallel processing
using decks of cards] or https://goo.gl/Wf1cvD[routing using toothpicks and
marshmallows].

As one assignment, students were required to submit their own videos
explaining course content.
//
To grade these assignments, we modified the https://hotcrp.com/[HotCRP] paper
reviewing system to simplify staff grading.
//
A similar approach could be used in the future to support peer video grading.

=== Contributions to the Discipline

Starting in Fall 2015 I led a
//
https://goo.gl/w8J5u3[holistic overhaul of UB's Computer Science curriculum].
//
Leading a team of faculty and students, we managed to modernize and streamline
the curriculum while meeting
//
http://www.abet.org/accreditation/accreditation-criteria/criteria-for-accrediting-computing-programs-2017-2018/[ABET]
//
and
//
http://www.suny.edu/attend/get-started/transfer-students/suny-transfer-paths/pdf/transferSUNY_Computer_Science.pdf[SUNY Seamless Transfer]
//
constraints.
//
https://goo.gl/w8J5u3[The new curriculum] includes completely revamped
introductory programming and theory sequences.
//
It eliminates unnecessary requirements that had crept into the program over
the years, and thereby increases the number of electives from 4 to 7.
//
As a core part of the process, we performed a
//
https://goo.gl/Qd2rWu[careful analysis of curricula at multiple other institutions],
//
coding them for the purposes of comparison.

A significant part of the new curriculum is a new set of introductory
programming courses.
//
I designed these courses with help from other faculty members.
//
Our goal was to produce a modern, rigorous, and accessible introduction to
both programming as a skill and computer science as an intellectual
discipline.
//
We produced a https://goo.gl/brdQOO[detailed design document] for the two new
courses, as well as shorter descriptions of https://goo.gl/GbWbsB[P1] and
https://goo.gl/eXwSmv[P2].

The new curriculum will begin to go into effect in Fall 2017 and be fully
realized by Fall 2018.
//
The new introductory courses will also be taught for the first time during
this period.

=== Other Accomplishments

In addition to the contributions described above, I have also been involved in
a variety of other teaching-related activities:

. I have served on the Undergraduate Advisory Committee for the CSE department
since 2011.
//
My link:/people/challen@buffalo.edu/GeoffreyChallen-Service.pdf[service
statement] describes this and other departmental and professional service
activities.
//
. I have developed and disseminated high-quality educational materials, both
through course web sites (https://www.ops-class.org[`ops-class.org`]), online
videos (https://goo.gl/nepnjM[OS], https://goo.gl/oQRerI[Internet]), and
open-source tools (https://test161.ops-class.org[`test161`]).
//
. I have secured link:/proposals/[a large amount of external funding].
//
Components of link:/proposals/2016-career-maybe/[my CAREER award] support
educational innovation.
//
I have also received internal funding from
//
http://www.buffalo.edu/ubcei.html[UB's Center for Educational Innovation]
//
to support developing our new introductory courses.
//
. I have designed and led educational outreach programs.
//
I started and have served as the faculty mentor for
//
https://www.facebook.com/ubscientista/[UB's chapter of the Scientista Foundation].
//
http://www.scientistafoundation.com/[Scientista] is a national organization
dedicated to advancing women in STEM.
//
I have also served as the faculty mentor for
//
https://ubacm.org/[UB's chapter of the ACM].
//
. I have supervised a link:/people/[number of students] at both the graduate
and undergraduate level.
//
In addition to research done by my Ph.D. students, I have also supervised
multiple undergraduate research projects.
//
https://www.bluegroup.systems/people/nvdirien/[Nick DiRienzo] published
several papers as a member of my group.
//
https://www.bluegroup.systems/people/gjbunyea/[Greg Bunyea] has had a
significant role in the development of our Internet seminar as the head
undergraduate teaching assistant.
//
. I have contributed to scholarship in my discipline.
//
Please see our group's link:/projects/[projects] and
link:/papers/[publications] page for details of our work in mobile systems and
networking.

== Biography

I lead the link:/[blue Systems Research Group] and also direct the
http://www.phone-lab.org[PhoneLab].
//
My research interests are in systems and networking, mobile systems, and
smartphones.
//
I teach an https://www.ops-class.org[introduction to computer operating
systems], a http://www.internet-class.org[new freshman course on the
internet], and a link:/courses/ub-720-fall-2016/[graduate seminar] covering a
variety of contemporary topics in mobile systems.

Please link:/people/gwa/[click here] for a longer biography.

// vim: ts=2:sw=2:et
