---
name: "A Walk on the Client Side: Monitoring Enterprise Wifi Networks Using Smartphone Channel Scans"
published: infocom
people:
- jinghaos
- lmeng@nd.edu
- striegel@nd.edu
- qiao
- dimitrio
- challen
projects:
- pocketsniffer
funding:
- 2011-cri-phonelab
git: https://github.com/blue-systems-group/papers.infocom16-scan.git
---
== Abstract

During the one minute it takes to read this abstract, 2 billion smartphones
worldwide will perform billions of Wifi channel scans recording the signal
strength of nearby Wifi Access Points (APs). Yet despite this ongoing
planetary-scale wireless network measurement, today few systematic efforts
are made to recover this potentially valuable data.

In this paper we ask the question: "Are the smartphone channel scans useful
in monitoring enterprise Wifi networks?" More specifically, can these
client-side measurements provide new insights compared to the AP-side
measurements that enterprise Wifi networks already perform? Beginning with
two Wifi scan datasets collected on two large scale smartphone testbeds, we
conduct case studies that show how smartphone channel scans can be used to
(1) improve AP spectrum management, and (2) predict the impact of AP failure
or overload. In each case, a walk on the client side yields valuable insights
for network operators that are otherwise impossible to gain from AP-side
measurements, and together our results demonstrate the value of smartphone
channel scans.
