---
name: Improving Smartphone Sustainability
title: Improving Smartphone Sustainability by Reusing Discarded Devices
started: 2013-06-01
ended: 2014-02-26
people:
- sriramsh
- ans25
- gurupras
- anudipam
- shaseley
- mpuri2
- junfeiwa
- challen
papers:
- hotmobile2014-sustainability
---

[.lead]
Electronic waste is a growing problem as the rapid pace of technological
improvements drives consumer appetites for the latest and greatest devices.
Smartphones are already part of this problem, and given the rate of progress
in the smartphone technologies, it seems reasonable to expect that consumers
will dispose of these devices at rapid rates, spurred on by new features and
discounts offered by carriers. Fortunately, the capabilities of smartphones
make discarded devices ideal _building blocks_ for many second uses. We have
explored reusing the discarded smartphones generated by
link:/projects/phonelab[PhoneLab] in multiple ways: as
link:/papers/hotmobile2014-sustainability[environmental sensors], to create a
city-scale sensor network, and as part of
link:/projects/pocketlocker[personal storage clouds].

== Overview

Smartphone technologies are advancing rapidly, bringing new power into users
pockets and changing the way that we live and work. The rapid rate at which
consumers purchase new smartphones can be seen as primarily a response to the
rate at which this technology is improving. Short device lifetimes, while
unfortunate from a sustainability perspective, help support companies that
build and sell smartphone hardware and software. Unfortunately smartphones,
like most other electronics, are difficult to dispose of properly. Many end
up in landfills or shipped to poor countries where they are dangerously
dismantled in an effort to collect precious materials.

Given the potential of the smartphone to bring about transformative
technological change, it becomes difficult to reduce *demand* by arguing that
consumers should hang on to outdated devices in the name of sustainability.
Instead, we propose to focus on the *supply* of fully- or
partially-functional outdated devices that society currently struggles to put
to use, and explore how this growing volume of techno-trash can be
efficiently reused.

There are three reasons why the time is right for this effort. First, unlike
previous generations of "feature phones", the current smartphone market is
coalescing around a small set of common platforms such as Android. This
platform homogeneity reduces the burden of supporting large numbers of
discarded devices. Second, current smartphones have an attractive feature set
for many non-phone applications: size and power requirements facilitating
easy deployment, microphones and cameras allowing them to double as sensors,
touch screens for interfacing with users.

Finally, smartphones are well-integrated into the existing communication
infrastructure. They can transmit data via text messages, over Wifi networks,
and via high-speed mobile communication technologies like 3G. If Wifi is
available, no service plans are required to allow recycled smartphones to
become part of the "Internet of Things". And with carriers increasingly
interested in "machine-to-machine" applications, we expect to see increasing
service flexibility allowing discarded devices to be cheaply connected to
pervasive mobile cellular and data networks.

To provide an idea of the potential of discarded devices, the U.S.
Environmental Protection Agency (EPA) estimated that 141~million mobile
devices became ready for end-of-life management in 2009, of which only 11.7
million (8%) were collected for recycling. The 129~million phones discarded
in 2009 would be enough to place an average of _200 phones_ on all
600,000~bridges in the United States, or every _2 feet_ on every stretch of
highway in the 46,876~mile interstate highway system.

== Summary

Inspired by the several hundred discarded devices link:/[blue] receives
through the link:/projects/phonelab/[PhoneLab project], we set out to explore
several potential second uses--particularly to facilitate other ongoing
research efforts. Our link:/papers/hotmobile2014-sustainability[HotMobile'14]
paper takes a cheeky turn on the project by suggesting that discarded
smartphones would be an ideal replacement for many of the uses originally
imagined for sensor network "motes". Since then we have continued to leverage
our supply of discarded smartphones for multiple purposes:

* University at Buffalo Linguistics Professor
http://www.acsu.buffalo.edu/~jcgood/[Jeff Good] has taken several of our
discarded devices to Cameroon to help preserve a dying language.
* We are turning discarded smartphones into navigation devices as a way to
"sneak into cars" as part of the link:/projects/navjack/[Navjack project].
* We are investigating multiple ways to allow users to continue to use
discarded smartphones as part of a growing "personal cloud" of devices--for
example, to provide additional storage available to other nearby devices.

We have been assisted in our efforts by http://www.sprint.com[Sprint], which
has multiple ongoing sustainability efforts.
https://www.linkedin.com/in/darrendbeck[Darren Beck] has been particularly
supportive of our efforts.
